

export const TUTORIAL_CONST = {
  GET_TUTORIAL_REQUEST: "GET_TUTORIAL_REQUEST",
  GET_TUTORIAL_SUCCESS: "GET_TUTORIAL_SUCCESS",
  GET_TUTORIAL_FAILURE: "GET_TUTORIAL_FAILURE",

  ADD_TUTORIAL_REQUEST: "ADD_TUTORIAL_REQUEST",
  ADD_TUTORIAL_SUCCESS: "ADD_TUTORIAL_SUCCESS",
  ADD_TUTORIAL_FAILURE: "ADD_TUTORIAL_FAILURE",

  UPDATE_TUTORIAL_REQUEST: "UPDATE_TUTORIAL_REQUEST",
  UPDATE_TUTORIAL_SUCCESS: "UPDATE_TUTORIAL_SUCCESS",
  UPDATE_TUTORIAL_FAILURE: "UPDATE_TUTORIAL_FAILURE",

  GET_TUTORIAL_BY_ID_REQUEST: "GET_TUTORIAL_BY_ID_REQUEST",
  GET_TUTORIAL_BY_ID_SUCCESS: "GET_TUTORIAL_BY_ID_SUCCESS",
  GET_TUTORIAL_BY_ID_FAILURE: "GET_TUTORIAL_BY_ID_FAILURE",

  DELETE_TUTORIAL_REQUEST: "DELETE_TUTORIAL_REQUEST",
  DELETE_TUTORIAL_SUCCESS: "DELETE_TUTORIAL_SUCCESS",
  DELETE_TUTORIAL_FAILURE: "DELETE_TUTORIAL_FAILURE",

  DELETE_ALL_TUTORIAL_REQUEST: "DELETE_ALL_TUTORIAL_REQUEST",
  DELETE_ALL_TUTORIAL_SUCCESS: "DELETE_ALL_TUTORIAL_SUCCESS",
  DELETE_ALL_TUTORIAL_FAILURE: "DELETE_ALL_TUTORIAL_FAILURE",
};
